language: python

python:
  - "2.7"
  - "3.6"

# For linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq [build-essential, python-dev, openssl, libssl-dev, libevent-dev]

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - pytest